### ISSUE TITLE
Automate app build and release process

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/kolibri-installer-android#1]
@cyberorg Please implement this -
```
Whenever kolibri-installer-android-mss app is to be released:

git checkout and pull to /home/mssadmin/kolibri-installer-android from studycircle or whatever release branch name is passed
for each facility_id in http://content.myscoolserver.in/configs/ on MSS cloud server
	read the uncommented lines after "#content for active grades" from the http://content.myscoolserver.in/configs/<facility_id>/syncoptions.ini
	read the substrings prior to "_node_list" as grades from each uncommented line
	for each grade in grades:
		replace the following values in config.py -
			FACILITY_ID = facility_id
			GRADE = UPPERCASE(grade)
		make run_docker
		scp new apk to /var/www/html/configs/<facility_id>/Kolibri-MSS-{grade}.apk
```
Additionally, need to ensure that `http://content.myscoolserver.in/configs/` is not publicly browsable to ensure security of data therein.

**Comment by intelliant01** [comment]
@cyberorg Have done 
```
    location /configs {
        alias  /var/www/html/configs/;
        autoindex off;
        autoindex_exact_size off;
    }

```
for immediate security. This may need to be fine-tuned.

**Comment by cyberorg** [comment]
> for immediate security. This may need to be fine-tuned.

Good enough for our needs.

**Comment by cyberorg** [comment]
> @cyberorg Please implement this -
No, build the apk manually as needed till there is a single app released via play store, facility and grade selection should be available in the app UI which pulls required files from the server.

**Comment by intelliant01** [comment]
Single app for multiple facilities may not cut the cake ever. Branding etc, will always be needed. Taken a leaf from Moodle or imagine 100s of facilities listed to choose from.

Grade and user credentials is what will be needed for an app built for a facility and will be of much value only when user specific limited sync will be implemented. 

The above automated build process is needed to help accelerate the field testing scenarios and given the limited resources all are grappling with.

I shall take it up since you don't see the need for it. Thanks.

**Comment by intelliant01** [comment]
> Good enough for our needs.

Need configuration to hide beyond `configs/*/` but not `configs/*` . Is that possible?
